export enum Genre {
  Action = "Action",
  Adult = "Adult",
  Adventure = "Adventure",
  Anime = "Anime",
  Children = "Children",
  Comedy = "Comedy",
  Crime = "Crime",
  DIY = "DIY",
  Drama = "Drama",
  Espionage = "Espionage",
  Family = "Family",
  Fantasy = "Fantasy",
  Food = "Food",
  History = "History",
  Horror = "Horror",
  Legal = "Legal",
  Medical = "Medical",
  Music = "Music",
  Mystery = "Mystery",
  Nature = "Nature",
  Romance = "Romance",
  "Science-Fiction" = "Science-Fiction",
  Sports = "Sports",
  Supernatural = "Supernatural",
}
